label chapter_2:

"But, it should be fine."
Nemyu "I'll lead the way."
"I lead the way down the alley, and begin ascending the narrow metal stairway."
"Only curiosity wells up within me in this kind of situation."
Ely "Mightn't this be trespassing?"
Nemyu "I guess so, but..."
"I can't find a way to explain why that doesn't stop me."
Ely "Life is too dull to pass up an interesting opportunity, you think?"
"Ely seems to have long become accustomed to my predictable way of thinking."
Nemyu "That might be why. But I don't think I'm the only one that feels that way."
"Or else people wouldn't create things that nobody else has thought of, or read something that is completely new to them."
Ely "But I think most people would be too scared to do something like this."
Nemyu "Only because I can count on you to come with me."
"Although it wasn't always so."
"Reaching the open door, I peer inside to find a bland hallway with gray walls."
"There doesn't seem to be anyone around."
"I wave my hand for Ely to follow me, then head inside remorselessly."

stop music fadeout 2

"Ahh, I just can't help but to invite myself in."
"\"Urban exploration\", they call it? The hobby of prowling about and exploring abandoned urban buildings and sites."
"I suppose it's something like that; but I don't limit myself to abandoned structures."
"This city's unmappable network of architecture is more interesting than anywhere else, I bet."
"Ely seems a little unsure, but she knows the worse that can happen is we get kicked out. I'll take responsibility in any case."
"Around the corner at the end of the hallway, and through another door to the right, I hear a sound."

play music keyboard fadein 2 loop

"It's a faint tapping -- someone typing at a keyboard?"
"Ensuring that Ely is still behind me, I silently approach the door frame and peer around its edge."
"Indeed, there is someone typing on a keyboard, facing the opposite direction..."
"But more striking is what surrounds him."
"Dozens of monitors, from wide and slim to square and bulky, surround him. Lights blink on a multitude of devices that I don't recognize."
"Ely, who peers inside as well, is captivated with me by what those screens show."
"She stifles a small sound with her hand as she seems to realize what the monitors are showing."
"We're too slow to react when the door behind us is suddenly flung open, and a man in a business suit exits with us directly in his line of sight."
Man "Huh? Who are you two?"
Nemyu "Uh, us? We're..."

stop music
$ renpy.music.set_volume(1.0, delay=0, channel='music') #Slipped it in here so the AC units have time to stop

"I hear the guy in the room get up from his seat, drawn by the commotion."
"When he reaches the door and sees us, I avert my gaze bashfully. If we just ran away, they probably wouldn't bother to call the police, so..."
Guy "Ah, they're with me, don't worry Mike."
"Just then, a strong sensation assails my mind."
"What was that?"
Mike "Oh? Alright."
"The man, seemingly well acquainted with the guy, immediately believes him and resumes walking down the lengthy corridor."
"I don't know why he lied for us, but Ely attempts to casually remove ourselves from the situation."
Ely "Well, we should go, hehe..."
Guy "Hold on."
"I prepare for a firm lecture. This guy only looks to be in his very early twenties or even late teens, but has the confident glare that I'd expect from a powerful CEO-type person."
Guy "You two were spying on me just now?"
Nemyu "Well... Yeah, no getting around it huh."
"I put my hands together and give a sincere apology."
Nemyu "Sorry! We were just passing by, we'll leave now..."
"I just hope that he wasn't doing secret government business or anything. Then we'd be in more trouble than I could deal with..."
Guy "Hm, I don't know who you are or why you're here, but what, are you interested? I can show you around if you want."
"He smiles, as though happy that someone showed interest in what he was doing."
"Although we were just looking around randomly."
"However, Ely seems honestly interested in the proposal."
Ely "Really? You're doing something with today's satellite launch... right?"
"Oh, she realized that just from that small peek?"
"Then again, her father is heavily involved in the project, so I guess it isn't too surprising after all."
Guy "Yeah, that's right. C'mon, I'll show you."
Nemyu "Erm, are you sure that's okay?"
Guy "Hm? Oh yeah, it's not like I'm involved with the project, haha. Well, you'll see what I mean."
"He sits down on his chair as he begins to explain."
Guy "The thing about KOL20 is..."
"I'm fairly certain that's the name of the satellite that launched today."
Guy "... Even a random guy like me can connect to it as I please. Well, though only because I have a satellite dish of my own."
Guy "Ah, this random guy's name is Max, by the way."
"People like Max aren't uncommon in this city."
"When everybody pursues new and exciting technological developments, it's not surprising for their children to want to follow in their footsteps."
Nemyu "I'm Nemyu, and this is Ely."
Ely "So so, what kind of things can you do when connected?"
Max "Probably the most interesting thing about KOL is that it's essentially a new type of computer."
Max "Well, I think only the creators really understand it at the moment. The thing is that it generates so much heat that they've had to resort to sending it into orbit for it to be usable."
Ely "That's right! But wait, wouldn't that be even less effective than on Earth? Even though space is cold, it has no medium for the heat to dissipate into..."
Max "That's true, I'm glad you realized that. It seems that they've discovered some cooling trickery..."
"Admittedly, I lose interest in the conversation."
"As for Ely, I think that rather than being interested in the specifics of the satellite's operations..."
"She's just very proud of her father, isn't she?"
"She doesn't know a great deal about the satellite itself, but her face lights up in consideration of her father's achievements."
"I wonder how that feels..."
Max "... In any case, it looks like I'm going to be in queue for a while. You have to make an account and be confirmed to access KOL's systems, and there's already a huge waiting list..."
Ely "Ahh, pity. Oh-- Nem?"
"Ely pulls me out of my reverie."
Ely "Should we go back outside? There's still lots to see today."
"She probably noticed that I didn't have much interest in this talk."
"Not that I care much where we go or what we do, but..."
"On my mind is the unusual sensation I got earlier."
"Like a sixth sense that, for the first time, was activated."
Max "Say, do I know you from somewhere?"
"He addresses that question to me."
Max "From school maybe?"
Nemyu "No, don't believe so."
"More like, impossible."
Max "Hmm, though I'm certain I recognize you from somewhere..."
Nemyu "Not unlikely for you to have seen me about somewhere."
Max "Well, that's true."
Nemyu "In any case, what is this place? An office?"
Max "This building? Ah, it used to be."
Max "Now most of it is being rented out as private rooms. That's why I'm all set up here..."
"Indeed, I can see a couch that's being used as a bed sitting along the far wall."
"Then, possibly..."
Nemyu "I'll be right back, okay?"
"I say to Ely."
Ely "Ah, where are you going?"
Nemyu "Just gonna look around a little."
Ely "? Well okay, sure."
"I leave the slightly confused Ely behind, feeling apologetic."
"When I hear them continue to talk about their shared interest, I head down the hallway."

"As Max said, the building wasn't a normal office building."
"Exploring several floors upwards, I passed by numerous rooms with open doors and no furnishings."
"There were a few connecting passages to the adjacent building, which appeared to still be used as a workplace for some company."
"That's probably where the man that spotted us earlier headed."
"Quite a few rooms appeared to be occupied; being used as private work areas, or for storage."
"With the lack of the normal utilities, such as private kitchens or bathrooms, I doubt anybody was living in these rooms."
"... Though if they were cheap enough, I bet some would be drawn here."
"I'm on the tenth floor now, if I counted correctly."
"This staircase may be..."
#[Scene: Opening a door to the roof]
"The final one."
"I immediately notice that the wind up here is fairly strong, even on such a calm day."
"Crap, my hair is going to become a mess..."
"Still, I'm drawn to the fence that bounds the wide area, which is devoid of trash or blemishes. I guess it's rare for people to come up here."
"Curious, I take a bucket near the door and put it in the door frame, so that the door won't lock itself behind me."
"Not that it was locked in the first place, but you can call that my paranoia."
"I then make my way to the edge of the roof."
"From here, I can see the bay unhindered. The ocean gradually encompasses my view as my eyes rise to the horizon."
"With these waves of salty air blown in from the shore, I can barely feel the day's heat."
"Somehow, it's a tranquil place."
"Yet, all I can think is"
Nemyu "So unsatisfying..."
"It's a scene I should be able to enjoy."
"But its pleasures don't reach me. The more I feel that I should be at peace, the more frustrating it is that I'm not feeling it as I should be."
"Just what is it that is missing?"
"I look to the skies, already showing a tinge of orange from the early setting Sun."
"Sol, whose light has traveled 150 million kilometers to illuminate this scenery before me."
"If it did so for my sake alone, would that be enough to appease me?"
"Would that make this view mine alone?"
"The Moon shows itself too, not to be outdone even in the evening."
"In front of it is a dim light, blinking green."
"KOL? Who knows. There are dozens of artificial satellites that could be the cause."
"Or maybe just a plane, or something even less impressive."
Nemyu "I wonder, is anyone else sharing this view of mine?"
"Or can I call this one mine alone?"
UK "..."
Nemyu "!"
Nemyu "Oh, hello. I didn't notice you there."
UK "Allow me to give you a word of advice."
#A girl's voice.
#A girl's figure.
Nemyu "Advice? Sure..."
UK "Tonight..."
Nemyu "..."
UK "Don't be alone. Do you understand?"
Nemyu "... Sure I do. Though I don't know why you're saying that to me. Who are you?"
UK "You can spend the night with a friend, right? Make sure you do that."
Nemyu "You're saying some scary things. Listen, I'm Nemyu. What's your name?"
"I don't know if this girl is crazy or just bored, but I try to return the flow of conversation to something resembling normal."
"She seems to hesitate, but--"
Nemyu "Ah, hey!"
"The figure dashes off."
"I couldn't get a good look at her since she had been hiding in the shadow of a large vent."
"And before I know it, she's gone through the door and closed it behind her before I could even take a second step forward."
"Not really sure what to do, I decide to run after her."
#[Sound: Shakes door handle. It's locked]

play sound locked_door

Nemyu "Are you kidding me?!"
"She locked the door behind her!"
"What is wrong with that person?"
"Her words were threatening, but it was more like she was warning me."
"Some kid just playing a prank?"
"Most likely. Not like there's any reason for me to be in danger."
"I give the door handle a stronger shake, but it's solidly locked. Doesn't seem like I'll be able to get it open that easily."
"Though after glancing around the roof, there doesn't seem to be another way down."
"The tall fence surrounds the area without a single gap. The next building over sits touching this one, and is only slightly shorter, so I could climb the fence and jump down..."
"I consider that before realizing that I can simply send a message to Ely."
Nemyu "No need to pointlessly exert myself..."
"I write a quick text message and press the send button."
Nemyu "Seriously though, what kind of place lets a door lock this way?"
"Accidents happen. It's only logical to have a door like this open from the outside, whether it's locked or not."
"I'm fairly certain there are laws ensuring it, in fact..."
"Was it something that was simply overlooked?"

#[Scene: Door being opened]
Ely "Nemyu! What're you doing up here?"
Ely "You're not usually the type to get yourself locked out somewhere..."
"Effortlessly swinging the door open from inside, Ely emerges as I'm leaning against a vent, with Max following behind."
Nemyu "And you'd be right. I left the door open, but someone locked me up here..."
Ely "What? Who would do something like that!"
"She looks around with a glare, as if the culprit were waiting around to be caught."
Nemyu "No clue. They ran off before I could get a chance to see."
Max "Uhm..."
Nemyu "Hm? What is it?"
"The guy is still standing near the door, with a troubled look on his face."
Max "Well, it's not like I don't believe you. But this door doesn't lock."
Nemyu "Huh? Are you sure?"
"He points to the handle mechanism. As he says, there's no lock on the door. There's no way at all it could've been kept closed."
Nemyu "That's strange..."
"It was definitely locked. The door swings outwards, so there was no obstacle in the way. And unlike if the culprit had been pulling the door closed as I struggled to open it, the rattling of the door was undoubtedly due to some kind of bolt-like obstacle."
Ely "Doors like these are always made to be opened from the outside in any case."
Nemyu "It must've been my imagination..."
"For now I try to tie the issue up. I'd rather leave now than stick around for no reason."
Ely "That's so unlike you though Nem... But maybe it was just that."
Nemyu "Anyway, let's head back down. It's starting to get chilly up here."
"The other two nod in agreement."
Max "Ah, you said you at least saw someone up here, right? What did they look like? There's a chance it could be someone I've seen around here before."
Nemyu "All I could tell is that it was a short girl. Wearing baggy clothes, I think."
"Max appears to search his memory, but soon shakes his head with a sigh."
Max "Sorry, no clue. But I'll stay on the lookout."
Nemyu "I'd appreciate that."
"I'd hate to have to accept that I simply had a sudden, vivid hallucination like that."
"It's slightly concerning to think that some stranger was, or still is, stalking me, but having severe hallucinations with no obvious cause is quite a bit more terrifying to me."
"At least other people can be dealt with, no matter how dangerous they are."
"When your own body is the assailant that you have to be careful of, you can't help but curse your inability to do anything about it."
"That's what I fear most."
#Scene Change?
"With the sun setting and the warmth of the day dissipating into the cloudless sky, Ely and I decide to begin heading home."
"We left Max behind to explore the festivities some more, and the afternoon soon began drawing to a close."
"I live rather far from the city center, in a town called Kaligaya. It'll be still be some time on the train before I can get back home for the night."
"We're heading towards the train station when Ely hesitantly begins to speak."
Ely "So uh, this person you saw earlier... Did they say anything to you?"
"She hadn't brought it up while we were walking around town, but it looks like this has been on her mind."
"From an outside perspective, I must've seemed pretty out of it, saying the things I did."
"But I only truthfully told what happened."
"And I'm not one to joke around or pull pranks. My naturally expressionless face often makes people unsure of what my intentions are..."
"So I can understand why Ely would be disconcerted."
"And since she's someone I can trust, there's not reason not to simply tell her the truth."
Nemyu "She told me that I should avoid being alone tonight. Then she just ran off."
Ely "Huh? Hm... And you're sure you don't know who it was?"
Nemyu "Yeah. There're not many options to choose from in the first place."
Ely "Kinda creepy though, don't you think?"
Nemyu "I suppose. But I don't see how anything bad could happen."
Nemyu "Curses and the like don't exist, and muggers don't send out girls to warn their victims in advance. Rather than feeling scared, I just feel reassured that the most worrying thing in this city is the prank of some kid."
"It sounds like an excuse, when I hear my own words; but as I've been prone to strolling about the streets at all hours of the night since I was a child, I know well that there're no ghostly horrors worth minding in this city."
"Other children apparently go through a long stage where the dark terrifies them, sometimes never growing out of it."
"That's just something I've never personally experienced, fortunately."
Ely "Even so, that makes me a little worried about sending you off by yourself..."
Nemyu "That's unusual for you. Don't you love the horrors of the night, Miss \"Fleurdelice\"?"
Ely "Ahhhhh! Don't say that in public!"
"She hushes me with a face blushing from embarrassment."
Nemyu "Oh? That is your 'Vampire Name', isn't it?"
Ely "Urgh. I don't really do that anymore, you know..."
Nemyu "You sure?"
"I gesture to her clothing, but she pretends not to notice."
"Most people wouldn't think this at a glance, but there's a distinct 'gothic lolita' theme to her outfit."
"Enough to draw attention, but not to the degree that she really stands out."
"A strange balance between showing off what she loves and being careful of her public image..."
Ely "Hmph. You're imagining things. If you're not careful, I might just gouge out your neck..."
"She bares her fangs, actually oddly vampiric in a way."
"A unique threat."
"But shouldn't you make up your mind?"
Ely "But this is as good a chance as any, don't you think?"
Nemyu "Chance to do what?"
Ely "Have a sleepover! It's been forever since we've done anything like that."
Nemyu "Now that you mention it, yeah."
Nemyu "But there's school in the morning, right?"
"It's Sunday, so not the best night for something like this."
Ely "Eh, I can be a little late. Human rules mean nothing to me after all, haha!"
Nemyu "Mm, right."
"I work part-time on Monday and Tuesday, so fortunately I don't need to worry about school tomorrow. As for Ely, her grades are already not the best..."
Ely "I'll just feel concerned if you're left alone is all..."
"Her tone of voice is serious, and a little bit sad."
Nemyu "... Alright, I don't mind either way."
"I decide to give in. It would be nice to spend the night with someone else for once to be honest."
Ely "Great! I'll just text my mum to let her know!"
"We're already arriving at the train station, and it's beginning to get dark."
"I go through the routine of getting tickets and heading to the tracks to wait, ingrained in my mind after so many repetitions."
"The train arrives on the busy platform after a few minutes, and we set off for Kaligaya."
jump common4
