label common4:

scene train_interior with dissolve

"Several major stops away -- almost forty minutes of travel -- is the station for the town where I live."
"Ever since the price of rent drastically grew within the inner city, I've had to live at this distance from the city I know so well."
"Kaligaya is a normal town that suffers from the usual troubles of society, unlike the inner city."
"Admittedly, I still feel discomfort living away from the city I've known all my life..."
"But there's not much that can be done."
"Though that may no longer be true. That building earlier had plenty of spare rooms, which I imagine can't cost a lot."
"Moving back could certainly be possible, and then I wouldn't live so far from my necessities."
"But I can think about that later."
"Ely sits to my left, humming happily, while I look out through the darkness."
UK "Arriving at Kaligaya Station."
"I hear the announcement system as I awake from my half-asleep state, thanks to my phone vibrating in my pocket."
"I set it to vibrate when the train gets here, after almost sleeping through my stop one too many times... Thanks, past self."
Nemyu "As expected..."
"Ely is still next to me, breathing softly in a deep sleep."
"I quickly rouse her as the train pulls into the station."

play sound train_arriving fadein 3

"The train comes to a halt, and we languidly step off of the empty carriage into the cold night."

scene foggy_street with dissolve

"Looking out into the thick darkness that surrounds the station, I can't help but feel intimidated by the warning I received."
"Mist swirls across the concrete, ominous under the flickering overhead lights and dim glow of a vending machine"
"Before I've taken another step, the train door closes behind me, and the electric engine quietly propels it away and into the distance."
"Ely shivers, glancing about with what I guess to be similar thoughts to my own."
"Her arms mostly uncovered, she must be a lot colder than I am."
Nemyu "Alright, let's get home quickly..."
Ely "Y-yeah."
"An unlit stretch of land lies between us and the dimly lit streets of the town itself."
"Was it always this dark?"
"I can't manage to take a step forward, as though the chill has already frozen me to the spot..."
"Damn, to think I'd be affected this much."
"I sweep the area without blinking, but can't see much of anything within the veil of black."
"I'm unable to even recall what the path even looks like..."
"Feeling as though I'm standing ashore a bottomless river, I look to the liveliness of the opposite shore and--"
Ely "Alright, let's race!"
"Ely bounds forward into my vision, and takes off into the darkness."
Nemyu "Wha--"
"Turning around, her bright irides seem to glow like a beacon."
Ely "C'mon!"
"Not allowing me a chance to think, she dashes off again."
"Of course, I chase after her."
"Standing there alone is even worse."
Ely "Compared to the light of the Sun, a bit of darkness isn't scary at all, you know!"
Ely "The darkness is my home, and yours too!"
"What is this girl saying..."
Nemyu "Hehe."
"I chase her phantom, until I finally and uneventfully reach the yellow light of a street light."
"But she's not there."
Nemyu "Ely?"
"There's no longer any sign of her--"
Ely "Nom."
"Behind me before I know it, she bites at my neck."
Nemyu "..."
"Sharp canines almost pierce my skin, but I have no energy to even wince."
Ely "Anyway,"
Ely "Hurry and escort me home, Nemmy."
Nemyu "R-right..."
"Contrary to just earlier, I'm feeling upbeat for once."
"Maybe hanging out with Ely again was all I needed after all. No need to dwell on things."
"I walk up to her side and we follow the road home."
#[The scene lingers as the two walk away, and after a while, unnatural footsteps (or something creepier?) are heard before the scene ends. Perhaps have one of the street lights shatter. Spooky...]
jump common5
