label common6:

"It's better to be safe."
"I'm always prepared to find a new workplace, anyway."
"Walking back in the direction I came, the unpleasant attacks on my body begin to fade away."
"As long as it disappears, the 'why' is unimportant."
"I free myself from worry by forgetting about it."
"Instead, I daydream about how I'll spend my night."
"I wonder if Ely would visit again?"
"It's fun to be with her instead of being alone."
"And it feels as if nothing bad can happen when she's around."
"Now that I think about it, I probably don't show my appreciation for her enough."
"She's my only real friend."
"What would I do if I lost her, I wonder?"
#She bumps into someone
Nemyu "Ah!"
"Suddenly, I'm sitting on the ground."
Nemyu "Oops, sorry. I wasn't looking where I was going."
"A tall silhouette holds their hand out towards me."
? "Don't worry, it was my fault."
"It feels as though my brain snaps."
"For just an instant..."
"A strange sensation. I've felt it before."
"Mild nausea assails me; I feel the same as I did standing in front of that tunnel just minutes ago."
"I shake my head to will it away."
"Fortunately, it passes quickly."
"Though still feeling weak, I manage to take his outstretched hand."
"Even though I'm standing now, he's still over a head taller than me."
"Ah, he's wearing Palisade High's uniform. I wonder if Ely knows him."
? "Are you alright? Your face is pale."
"His voice is deadpan and he looks bored as he asks if I'm okay."
"A straightforward kind of guy, huh?"
Nemyu "Yeah, I'm fine. Thanks."
"I make to leave, but--"
UK "Wait."
"His voice compels me to stop."
Nemyu "What is it?"
UK "Are you a student? You look younger than me."
Nemyu "Looks can be deceiving."
UK "... But you are younger than me. It's been less than nine months since your seventeenth birthday."
"... Lucky guess."
Nemyu "So, why does it matter?"
UK "Oh, curiosity. Why don't you go to school?"
Nemyu "Not everyone has such luxury, sorry to say."
UK "Luxury... I can't say I understand. Is tedium a luxury?"
Nemyu "It can be, if you're not used to it."
"Great. If I'm not careful, I'm going to end up sounding like a nagging mother."
UK "Hm? Anyway, pity. What is your name?"
Nemyu "You can call me N."
UK "Hah. Too suspicious, am I? Sorry about that. I'm poor at conversation."
UK "But not much else."
UK "I'm ?. See you, N."
"He slinks away."
"And a feeling of constriction that I hadn't even noticed surrounding me until now suddenly disperses."
Nemyu "Let's avoid him from now on."
"He probably didn't mean any harm, but you can never be too careful with people like that."
"If someone acts suspiciously, it usually means that they are suspicious."
"Feeling less tense now, I notice Ely running towards me."
Ely "Nem! Hey!"
"As she catches her breath, a couple other girls catch up to her."
"These must be her classmates."
Ely "These are my friends from class, Girl and Girl 2. I thought it'd be cool if we could all hang out this evening."
"They're staring at me with an expectant glow in their eyes."
Nemyu "? You want me to do a trick?"
Girl "Yeah! Yeah!"
"She responds to my nonsense."
Nemyu "Alright."
"I extend my arm for a handshake."
"The girl takes it, but then..."
Girl "Ah--"
"My hand detaches."
Girl_2 "N-no way..."
Girl "*collapses*"
Ely "Yes! As expected of Nem, you've learned supernatural powers yourself!"
"She plays along with it, but I feel bad seeing how shocked the girls are."
"I take back my hand and re-attach it."
Nemyu "It's a prosthetic."
Girl_2 "B-but, it's so realistic."
Ely "That's just how they are these days."
Ely "Honestly, I almost forgot about that. You surprised me too."
Girl "That's amazing, amazing!"
"She seems fine now."
"My first impression apparently lives up to the expectations of the two."
"I can't even guess what Ely has said about me."
Ely "Oh yeah, Nem, I saw that you were talking to ?. Was he bothering you?"
Nemyu "Your first thought was that he was doing something bad. It seems avoiding him would be for the best after all."
Ely "Ah! Well, I wouldn't really say that..."
Girl_2 "He's always mumbling to himself."
Girl "But, but! He never exactly does anything bad."
Girl_2 "I think staring at girls all the time counts as 'bad'."
Girl "True. He stares at other guys and teachers too. I don't get it."
"Regardless of his notoriety, my meeting him feels like a bad omen."
"I can't stop thinking about the unnatural reaction I felt when I bumped into him."
Nemyu "Crap, I have to get back to work."
"It slipped my mind for a moment, but I can't waste much more time."
Ely "Wa! You're right, sorry--"
Nemyu "It's fine. Let's meet up at five?"
"I ask the others too. They seem to be friendly."
"We agree to meet up at the mall."
"I've known Ely for so long yet never met her friends before today. This is a good chance to get closer to a normal life, something I've put off for so many years."
"My life feels like it's at the tip of a roller-coaster, ready to plunge into something new at any time."
"There's no obvious reason for it."
